### ISSUE TITLE
Missing Licensing Information

### ISSUE THREAD

**Issue by JMAlego** [Speldosa/DMXmidiator#1]
Hi there 👋

I'm the maintainer of [PyDMX](https://github.com/JMAlego/PyDMX) and I noticed that you are using a copy of the PyDMX code in this project. However, you haven't attributed that code and you haven't included the license.

PyDMX is licensed under the BSD 3-Clause License which requires you to retain copyright attribution and license (as well as a few other things, you can find more info about the BSD 3-Clause License [here](https://choosealicense.com/licenses/bsd-3-clause/) or read the [PyDMX license](https://github.com/JMAlego/PyDMX/blob/master/LICENSE)).

If you'd like to continue embedding that code in your project, you will need to update your project to provide the required licensing information. Alternatively, you can depend on the packed version of PyDMX which is on PyPi [here](https://pypi.org/project/PyDMX/).

As a further note, you've licensed your project under the GPL v3 License which _is_ compatible with the BSD 3-Clause License so you _don't_ need to worry about license incompatibility, just attribution and license information.

I'm always pleased to see people using my code - so don't be dissuaded from using it, that's what Open Source code is all about! - you just need to meet the requirements of the license to continue using it.

**Comment by Speldosa** [comment]
Sorry for not having included that information already (I had it on my todo list on this newly created project).

Anyhow, I think that I've included all the necessary information now. I stated that I use a modified version of PyDMX in my `Readme` and I included the license text in my `License` file. Let me know if there's something I've missed.

**Comment by JMAlego** [comment]
Thanks for doing that so quickly! You've done more than enough to make me happy with it (I would have been fine with just the license file).

Newer versions of PyDMX will contain the license in each file to make this easier on people who want to embed it, like you have.
